#include QMK_KEYBOARD_H

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {

    /* DEFAULT */
	LAYOUT_ortho_5x4(
		MO(1), KC_PSLS, KC_PAST, KC_PMNS,
		KC_P7, KC_P8, KC_P9, KC_NO,
		KC_P4, KC_P5, KC_P6, KC_PPLS,
		KC_P1, KC_P2, KC_P3, KC_NO,
		KC_P0, KC_DOT, KC_NO, KC_PENT),

    /* FUNCTION */
	LAYOUT_ortho_5x4(
		KC_TRNS, UG_TOGG, UG_NEXT, KC_TRNS,
        UG_HUEU, UG_SATU, UG_VALU, KC_TRNS,
        UG_HUED, UG_SATD, UG_VALD, KC_TRNS,
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
		KC_TRNS, QK_BOOT, KC_TRNS, KC_NUM)
};
