#include QMK_KEYBOARD_H

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {

    /* DEFAULT */
	LAYOUT_ortho_5x4(
                MO(1), KC_PSLS, KC_PAST, KC_PMNS,
		KC_P7, KC_P8, KC_P9, KC_NO,
		KC_P4, KC_P5, KC_P6, KC_PPLS,
		KC_P1, KC_P2, KC_P3, KC_NO,
		KC_P0, KC_DOT, KC_NO, KC_PENT),

    /* FUNCTION */
	LAYOUT_ortho_5x4(
		KC_TRNS, RGB_TOG, RGB_MOD, KC_TRNS,
        RGB_HUI, RGB_SAI, RGB_VAI, KC_TRNS,
        RGB_HUD, RGB_SAD, RGB_VAD, KC_TRNS,
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
		KC_TRNS, QK_BOOT, KC_TRNS, KC_NLCK)
};
