
#pragma once

#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_LED GP25
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_TIMEOUT 500U

// Add parity enable (but not _EPS, so odd).
#define UART_RP_LCR_H (UART_UARTLCR_H_WLEN_8BITS | UART_UARTLCR_H_FEN | UART_UARTLCR_H_PEN)
